export const INC_COUNT = "INC_COUNT"
export const DEC_COUNT = "DEC_COUNT"
export const GET_ALL_LATEST_TODO_LOADING = "GET_ALL_LATEST_TODO_LOADING";
export const GET_ALL_LATEST_TODO_SUCCESS = "GET_ALL_LATEST_TODO_SUCCESS";
export const GET_ALL_LATEST_TODO_FAILURE = " GET_ALL_LATEST_TODO_FAILURE"; 
 


